# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class 689Raw(models.Model):
    id = models.AutoField(db_column='ID')  # Field name made lowercase.
    insert_date = models.DateTimeField()
    edi_filename = models.CharField(db_column='EDI_filename', max_length=100)  # Field name made lowercase.
    eventcd = models.CharField(max_length=50)
    eventid = models.IntegerField()
    changed = models.DateTimeField(blank=True, null=True)
    filename = models.CharField(max_length=100, blank=True, null=True)
    notestext = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = '689_raw'


class 695(models.Model):
    eventcd = models.CharField(max_length=50)
    eventid = models.IntegerField()
    optionid = models.SmallIntegerField()
    serialid = models.SmallIntegerField()
    scexhid = models.IntegerField()
    bbcid = models.IntegerField()
    bbeid = models.IntegerField()
    actflag = models.CharField(max_length=50)
    changed = models.DateTimeField()
    created = models.DateField()
    secid = models.IntegerField()
    issid = models.IntegerField()
    isin = models.CharField(max_length=50)
    uscode = models.CharField(max_length=50, blank=True, null=True)
    issuername = models.CharField(max_length=50)
    cntryofincorp = models.CharField(max_length=50)
    sic = models.SmallIntegerField(blank=True, null=True)
    cik = models.IntegerField(blank=True, null=True)
    indusid = models.SmallIntegerField(blank=True, null=True)
    sectycd = models.CharField(max_length=50)
    securitydesc = models.CharField(max_length=100)
    parvalue = models.FloatField(blank=True, null=True)
    pvcurrency = models.CharField(max_length=50)
    statusflag = models.CharField(max_length=50)
    primaryexchgcd = models.CharField(max_length=50, blank=True, null=True)
    bbgcurrency = models.CharField(max_length=50, blank=True, null=True)
    bbgcompositeglobalid = models.CharField(max_length=50, blank=True, null=True)
    bbgcompositeticker = models.CharField(max_length=50, blank=True, null=True)
    bbgglobalid = models.CharField(max_length=50)
    bbgexchangeticker = models.CharField(max_length=50)
    structcd = models.CharField(max_length=50, blank=True, null=True)
    exchgcntry = models.CharField(max_length=50)
    exchgcd = models.CharField(max_length=50)
    mic = models.CharField(max_length=50)
    micseg = models.CharField(max_length=50, blank=True, null=True)
    localcode = models.CharField(max_length=50)
    liststatus = models.CharField(max_length=50)
    date1type = models.CharField(max_length=50)
    date1 = models.DateField(blank=True, null=True)
    date2type = models.CharField(max_length=50, blank=True, null=True)
    date2 = models.DateField(blank=True, null=True)
    date3type = models.CharField(max_length=50, blank=True, null=True)
    date3 = models.DateField(blank=True, null=True)
    date4type = models.CharField(max_length=50, blank=True, null=True)
    date4 = models.DateField(blank=True, null=True)
    date5type = models.CharField(max_length=50, blank=True, null=True)
    date5 = models.DateField(blank=True, null=True)
    date6type = models.CharField(max_length=50, blank=True, null=True)
    date6 = models.DateField(blank=True, null=True)
    date7type = models.CharField(max_length=50, blank=True, null=True)
    date7 = models.DateField(blank=True, null=True)
    date8type = models.CharField(max_length=50, blank=True, null=True)
    date8 = models.CharField(max_length=1, blank=True, null=True)
    date9type = models.CharField(max_length=50, blank=True, null=True)
    date9 = models.CharField(max_length=1, blank=True, null=True)
    date10type = models.CharField(max_length=50, blank=True, null=True)
    date10 = models.DateField(blank=True, null=True)
    date11type = models.CharField(max_length=50, blank=True, null=True)
    date11 = models.DateField(blank=True, null=True)
    date12type = models.CharField(max_length=50, blank=True, null=True)
    date12 = models.DateField(blank=True, null=True)
    paytype = models.CharField(max_length=50, blank=True, null=True)
    rdid = models.IntegerField(blank=True, null=True)
    priority = models.SmallIntegerField(blank=True, null=True)
    defaultopt = models.BooleanField()
    outturnsecid = models.IntegerField(blank=True, null=True)
    outturnisin = models.CharField(max_length=50, blank=True, null=True)
    ratioold = models.FloatField(blank=True, null=True)
    rationew = models.FloatField(blank=True, null=True)
    fractions = models.CharField(max_length=50, blank=True, null=True)
    currency = models.CharField(max_length=50, blank=True, null=True)
    rate1type = models.CharField(max_length=50, blank=True, null=True)
    rate1 = models.FloatField(blank=True, null=True)
    rate2type = models.CharField(max_length=50, blank=True, null=True)
    rate2 = models.FloatField(blank=True, null=True)
    field1name = models.CharField(max_length=50, blank=True, null=True)
    field1 = models.CharField(max_length=50, blank=True, null=True)
    field2name = models.CharField(max_length=50, blank=True, null=True)
    field2 = models.CharField(max_length=50, blank=True, null=True)
    field3name = models.CharField(max_length=50, blank=True, null=True)
    field3 = models.CharField(max_length=50, blank=True, null=True)
    field4name = models.CharField(max_length=50, blank=True, null=True)
    field4 = models.CharField(max_length=50, blank=True, null=True)
    field5name = models.CharField(max_length=50, blank=True, null=True)
    field5 = models.CharField(max_length=50, blank=True, null=True)
    field6name = models.CharField(max_length=50, blank=True, null=True)
    field6 = models.CharField(max_length=50, blank=True, null=True)
    field7name = models.CharField(max_length=50, blank=True, null=True)
    field7 = models.CharField(max_length=50, blank=True, null=True)
    field8name = models.CharField(max_length=50, blank=True, null=True)
    field8 = models.BooleanField(blank=True, null=True)
    field9name = models.CharField(max_length=50, blank=True, null=True)
    field9 = models.FloatField(blank=True, null=True)
    field10name = models.CharField(max_length=50, blank=True, null=True)
    field10 = models.CharField(max_length=50, blank=True, null=True)
    field11name = models.CharField(max_length=50, blank=True, null=True)
    field11 = models.CharField(max_length=50, blank=True, null=True)
    field12name = models.CharField(max_length=50, blank=True, null=True)
    field12 = models.CharField(max_length=50, blank=True, null=True)
    field13name = models.CharField(max_length=50, blank=True, null=True)
    field13 = models.CharField(max_length=1, blank=True, null=True)
    field14name = models.CharField(max_length=50, blank=True, null=True)
    field14 = models.CharField(max_length=50, blank=True, null=True)
    field15name = models.CharField(max_length=50, blank=True, null=True)
    field15 = models.TimeField(blank=True, null=True)
    field16name = models.CharField(max_length=50, blank=True, null=True)
    field16 = models.CharField(max_length=1, blank=True, null=True)
    field17name = models.CharField(max_length=50, blank=True, null=True)
    field17 = models.CharField(max_length=1, blank=True, null=True)
    field18name = models.CharField(max_length=50, blank=True, null=True)
    field18 = models.CharField(max_length=1, blank=True, null=True)
    field19name = models.CharField(max_length=50, blank=True, null=True)
    field19 = models.CharField(max_length=50, blank=True, null=True)
    field20name = models.CharField(max_length=50, blank=True, null=True)
    field20 = models.CharField(max_length=1, blank=True, null=True)
    field21name = models.CharField(max_length=1, blank=True, null=True)
    field21 = models.CharField(max_length=1, blank=True, null=True)
    field22name = models.CharField(max_length=1, blank=True, null=True)
    field22 = models.CharField(max_length=1, blank=True, null=True)
    field23name = models.CharField(max_length=1, blank=True, null=True)
    field23 = models.CharField(max_length=1, blank=True, null=True)
    field24name = models.CharField(max_length=1, blank=True, null=True)
    field24 = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = '695'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class EdiCa(models.Model):
    id = models.AutoField(db_column='ID')  # Field name made lowercase.
    ca_type = models.CharField(max_length=20, blank=True, null=True)
    created = models.DateField(blank=True, null=True)
    changed = models.DateTimeField(blank=True, null=True)
    eventid = models.CharField(max_length=20, blank=True, null=True)
    eventcd = models.CharField(max_length=20, blank=True, null=True)
    isin = models.CharField(max_length=20, blank=True, null=True)
    bbgcompositeticker = models.CharField(max_length=20, blank=True, null=True)
    issuername = models.TextField(blank=True, null=True)
    mic = models.CharField(max_length=20, blank=True, null=True)
    uscode = models.CharField(max_length=20, blank=True, null=True)
    effective_date = models.CharField(db_column='effective_Date', max_length=10, blank=True, null=True)  # Field name made lowercase.
    record_date = models.CharField(max_length=10, blank=True, null=True)
    payment_date = models.CharField(max_length=10, blank=True, null=True)
    start_subscription = models.CharField(max_length=10, blank=True, null=True)
    end_subscription = models.CharField(max_length=10, blank=True, null=True)
    gross_amount = models.FloatField(blank=True, null=True)
    net_amount = models.FloatField(blank=True, null=True)
    offered_price = models.FloatField(blank=True, null=True)
    old_mic = models.CharField(max_length=50, blank=True, null=True)
    new_mic = models.CharField(max_length=50, blank=True, null=True)
    old_issuer = models.TextField(blank=True, null=True)
    new_issuer = models.TextField(blank=True, null=True)
    ratio_old = models.FloatField(blank=True, null=True)
    ratio_new = models.FloatField(blank=True, null=True)
    currency = models.CharField(max_length=10, blank=True, null=True)
    spunoff_name = models.TextField(blank=True, null=True)
    spunoff_ticker = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'edi_ca'


class EdiCa1(models.Model):
    id = models.AutoField(db_column='ID')  # Field name made lowercase.
    created_date = models.DateTimeField()
    modified_date = models.DateTimeField(blank=True, null=True)
    edi_filename = models.CharField(db_column='EDI_filename', max_length=100)  # Field name made lowercase.
    old_edi_filename = models.TextField(db_column='old_EDI_filename', blank=True, null=True)  # Field name made lowercase.
    eventcd = models.CharField(max_length=50)
    eventid = models.IntegerField()
    optionid = models.SmallIntegerField()
    serialid = models.SmallIntegerField()
    scexhid = models.IntegerField()
    bbcid = models.IntegerField()
    bbeid = models.IntegerField()
    ca_type = models.CharField(max_length=20, blank=True, null=True)
    created = models.DateField(blank=True, null=True)
    changed = models.DateTimeField(blank=True, null=True)
    isin = models.CharField(max_length=20, blank=True, null=True)
    bbgcompositeticker = models.CharField(max_length=20, blank=True, null=True)
    issuername = models.TextField(blank=True, null=True)
    mic = models.CharField(max_length=10, blank=True, null=True)
    uscode = models.CharField(max_length=20, blank=True, null=True)
    effective_date = models.CharField(db_column='effective_Date', max_length=10, blank=True, null=True)  # Field name made lowercase.
    record_date = models.CharField(max_length=10, blank=True, null=True)
    payment_date = models.CharField(max_length=10, blank=True, null=True)
    start_subscription = models.CharField(max_length=10, blank=True, null=True)
    end_subscription = models.CharField(max_length=10, blank=True, null=True)
    gross_amount = models.FloatField(blank=True, null=True)
    net_amount = models.FloatField(blank=True, null=True)
    offered_price = models.FloatField(blank=True, null=True)
    old_mic = models.CharField(max_length=50, blank=True, null=True)
    new_mic = models.CharField(max_length=50, blank=True, null=True)
    old_issuer = models.TextField(blank=True, null=True)
    new_issuer = models.TextField(blank=True, null=True)
    ratio_old = models.FloatField(blank=True, null=True)
    ratio_new = models.FloatField(blank=True, null=True)
    currency = models.CharField(max_length=10, blank=True, null=True)
    spunoff_name = models.TextField(blank=True, null=True)
    spunoff_ticker = models.CharField(max_length=20, blank=True, null=True)
    old_isin = models.CharField(max_length=20, blank=True, null=True)
    new_isin = models.CharField(max_length=20, blank=True, null=True)
    old_ticker = models.CharField(max_length=20, blank=True, null=True)
    new_ticker = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'edi_ca1'


class EdiFdsCacm(models.Model):
    id = models.AutoField(db_column='ID')  # Field name made lowercase.
    created_date = models.DateTimeField()
    modified_date = models.DateTimeField(blank=True, null=True)
    edi_id = models.IntegerField(db_column='EDI_id', blank=True, null=True)  # Field name made lowercase.
    fds_id = models.IntegerField(db_column='FDS_id', blank=True, null=True)  # Field name made lowercase.
    ca_type = models.CharField(db_column='CA_type', max_length=50, blank=True, null=True)  # Field name made lowercase.
    ex_date = models.DateField(blank=True, null=True)
    isin = models.CharField(max_length=20, blank=True, null=True)
    ticker = models.CharField(max_length=20, blank=True, null=True)
    mic = models.CharField(max_length=10, blank=True, null=True)
    security_name = models.CharField(max_length=100, blank=True, null=True)
    record_date = models.CharField(max_length=10, blank=True, null=True)
    payment_date = models.CharField(max_length=10, blank=True, null=True)
    gross_amount = models.FloatField(blank=True, null=True)
    net_amount = models.FloatField(blank=True, null=True)
    currency = models.CharField(max_length=10, blank=True, null=True)
    old_ratio = models.FloatField(blank=True, null=True)
    new_ratio = models.FloatField(blank=True, null=True)
    old_value = models.CharField(max_length=100, blank=True, null=True)
    new_value = models.CharField(max_length=100, blank=True, null=True)
    spinoff_name = models.CharField(max_length=100, blank=True, null=True)
    spinoff_ticker = models.CharField(max_length=100, blank=True, null=True)
    start_subscription = models.CharField(max_length=10, blank=True, null=True)
    end_subscription = models.CharField(max_length=10, blank=True, null=True)
    fds_isin = models.CharField(max_length=20, blank=True, null=True)
    fsym_id = models.CharField(max_length=10, blank=True, null=True)
    fds_ticker = models.CharField(max_length=20, blank=True, null=True)
    fds_ex_date = models.DateField(blank=True, null=True)
    fds_ca_type = models.CharField(max_length=50, blank=True, null=True)
    fds_gross_div = models.FloatField(blank=True, null=True)
    fds_net_div = models.FloatField(blank=True, null=True)
    fds_currency = models.CharField(max_length=10, blank=True, null=True)
    fds_split_factor = models.FloatField(blank=True, null=True)
    fds_spinoff_value = models.FloatField(blank=True, null=True)
    fds_spinoff_factor = models.FloatField(blank=True, null=True)
    difference = models.FloatField(blank=True, null=True)
    sedol = models.CharField(max_length=20, blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    fds_proper_name = models.CharField(max_length=100, blank=True, null=True)
    active = models.BooleanField(blank=True, null=True)
    status = models.CharField(max_length=10, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'edi_fds_cacm'


class EdiMaster(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    created_date = models.DateTimeField()
    modified_date = models.DateTimeField(blank=True, null=True)
    edi_filename = models.CharField(db_column='EDI_filename', max_length=100)  # Field name made lowercase.
    old_edi_filename = models.TextField(db_column='old_EDI_filename', blank=True, null=True)  # Field name made lowercase.
    eventcd = models.CharField(max_length=50)
    eventid = models.IntegerField()
    optionid = models.SmallIntegerField()
    serialid = models.SmallIntegerField()
    scexhid = models.IntegerField()
    bbcid = models.IntegerField()
    bbeid = models.IntegerField()
    actflag = models.CharField(max_length=50)
    changed = models.DateTimeField()
    created = models.DateField()
    secid = models.IntegerField()
    issid = models.IntegerField()
    isin = models.CharField(max_length=100)
    uscode = models.CharField(max_length=100, blank=True, null=True)
    issuername = models.CharField(max_length=100)
    cntryofincorp = models.CharField(max_length=100)
    sic = models.CharField(max_length=100, blank=True, null=True)
    cik = models.CharField(max_length=100, blank=True, null=True)
    indusid = models.CharField(max_length=100, blank=True, null=True)
    sectycd = models.CharField(max_length=100)
    securitydesc = models.CharField(max_length=100)
    parvalue = models.CharField(max_length=100, blank=True, null=True)
    pvcurrency = models.CharField(max_length=100)
    statusflag = models.CharField(max_length=100)
    primaryexchgcd = models.CharField(max_length=100, blank=True, null=True)
    bbgcurrency = models.CharField(max_length=100, blank=True, null=True)
    bbgcompositeglobalid = models.CharField(max_length=100, blank=True, null=True)
    bbgcompositeticker = models.CharField(max_length=100, blank=True, null=True)
    bbgglobalid = models.CharField(max_length=100, blank=True, null=True)
    bbgexchangeticker = models.CharField(max_length=100, blank=True, null=True)
    structcd = models.CharField(max_length=100, blank=True, null=True)
    exchgcntry = models.CharField(max_length=100)
    exchgcd = models.CharField(max_length=100)
    mic = models.CharField(max_length=100)
    micseg = models.CharField(max_length=100, blank=True, null=True)
    localcode = models.CharField(max_length=100, blank=True, null=True)
    liststatus = models.CharField(max_length=100, blank=True, null=True)
    date1type = models.CharField(max_length=100, blank=True, null=True)
    date1 = models.CharField(max_length=100, blank=True, null=True)
    date2type = models.CharField(max_length=100, blank=True, null=True)
    date2 = models.CharField(max_length=100, blank=True, null=True)
    date3type = models.CharField(max_length=100, blank=True, null=True)
    date3 = models.CharField(max_length=100, blank=True, null=True)
    date4type = models.CharField(max_length=100, blank=True, null=True)
    date4 = models.CharField(max_length=100, blank=True, null=True)
    date5type = models.CharField(max_length=100, blank=True, null=True)
    date5 = models.CharField(max_length=100, blank=True, null=True)
    date6type = models.CharField(max_length=100, blank=True, null=True)
    date6 = models.CharField(max_length=100, blank=True, null=True)
    date7type = models.CharField(max_length=100, blank=True, null=True)
    date7 = models.CharField(max_length=100, blank=True, null=True)
    date8type = models.CharField(max_length=100, blank=True, null=True)
    date8 = models.CharField(max_length=100, blank=True, null=True)
    date9type = models.CharField(max_length=100, blank=True, null=True)
    date9 = models.CharField(max_length=100, blank=True, null=True)
    date10type = models.CharField(max_length=100, blank=True, null=True)
    date10 = models.CharField(max_length=100, blank=True, null=True)
    date11type = models.CharField(max_length=100, blank=True, null=True)
    date11 = models.CharField(max_length=100, blank=True, null=True)
    date12type = models.CharField(max_length=100, blank=True, null=True)
    date12 = models.CharField(max_length=100, blank=True, null=True)
    paytype = models.CharField(max_length=100, blank=True, null=True)
    rdid = models.CharField(max_length=100, blank=True, null=True)
    priority = models.CharField(max_length=100, blank=True, null=True)
    defaultopt = models.CharField(max_length=100, blank=True, null=True)
    outturnsecid = models.CharField(max_length=100, blank=True, null=True)
    outturnisin = models.CharField(max_length=100, blank=True, null=True)
    ratioold = models.CharField(max_length=100, blank=True, null=True)
    rationew = models.CharField(max_length=100, blank=True, null=True)
    fractions = models.CharField(max_length=100, blank=True, null=True)
    currency = models.CharField(max_length=100, blank=True, null=True)
    rate1type = models.CharField(max_length=100, blank=True, null=True)
    rate1 = models.CharField(max_length=100, blank=True, null=True)
    rate2type = models.CharField(max_length=100, blank=True, null=True)
    rate2 = models.CharField(max_length=100, blank=True, null=True)
    field1name = models.CharField(max_length=100, blank=True, null=True)
    field1 = models.CharField(max_length=100, blank=True, null=True)
    field2name = models.CharField(max_length=100, blank=True, null=True)
    field2 = models.CharField(max_length=100, blank=True, null=True)
    field3name = models.CharField(max_length=100, blank=True, null=True)
    field3 = models.CharField(max_length=100, blank=True, null=True)
    field4name = models.CharField(max_length=100, blank=True, null=True)
    field4 = models.CharField(max_length=100, blank=True, null=True)
    field5name = models.CharField(max_length=100, blank=True, null=True)
    field5 = models.CharField(max_length=100, blank=True, null=True)
    field6name = models.CharField(max_length=100, blank=True, null=True)
    field6 = models.CharField(max_length=100, blank=True, null=True)
    field7name = models.CharField(max_length=100, blank=True, null=True)
    field7 = models.CharField(max_length=100, blank=True, null=True)
    field8name = models.CharField(max_length=100, blank=True, null=True)
    field8 = models.CharField(max_length=100, blank=True, null=True)
    field9name = models.CharField(max_length=100, blank=True, null=True)
    field9 = models.CharField(max_length=100, blank=True, null=True)
    field10name = models.CharField(max_length=100, blank=True, null=True)
    field10 = models.CharField(max_length=100, blank=True, null=True)
    field11name = models.CharField(max_length=100, blank=True, null=True)
    field11 = models.CharField(max_length=100, blank=True, null=True)
    field12name = models.CharField(max_length=100, blank=True, null=True)
    field12 = models.CharField(max_length=100, blank=True, null=True)
    field13name = models.CharField(max_length=100, blank=True, null=True)
    field13 = models.CharField(max_length=100, blank=True, null=True)
    field14name = models.CharField(max_length=100, blank=True, null=True)
    field14 = models.CharField(max_length=100, blank=True, null=True)
    field15name = models.CharField(max_length=100, blank=True, null=True)
    field15 = models.CharField(max_length=100, blank=True, null=True)
    field16name = models.CharField(max_length=100, blank=True, null=True)
    field16 = models.CharField(max_length=100, blank=True, null=True)
    field17name = models.CharField(max_length=100, blank=True, null=True)
    field17 = models.CharField(max_length=100, blank=True, null=True)
    field18name = models.CharField(max_length=100, blank=True, null=True)
    field18 = models.CharField(max_length=100, blank=True, null=True)
    field19name = models.CharField(max_length=100, blank=True, null=True)
    field19 = models.CharField(max_length=100, blank=True, null=True)
    field20name = models.CharField(max_length=100, blank=True, null=True)
    field20 = models.CharField(max_length=100, blank=True, null=True)
    field21name = models.CharField(max_length=100, blank=True, null=True)
    field21 = models.CharField(max_length=100, blank=True, null=True)
    field22name = models.CharField(max_length=100, blank=True, null=True)
    field22 = models.CharField(max_length=100, blank=True, null=True)
    field23name = models.CharField(max_length=100, blank=True, null=True)
    field23 = models.CharField(max_length=100, blank=True, null=True)
    field24name = models.CharField(max_length=100, blank=True, null=True)
    field24 = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'edi_master'


class EdiRaw(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    insert_date = models.DateTimeField()
    edi_filename = models.CharField(db_column='EDI_filename', max_length=100)  # Field name made lowercase.
    eventcd = models.CharField(max_length=50)
    eventid = models.IntegerField()
    optionid = models.SmallIntegerField()
    serialid = models.SmallIntegerField()
    scexhid = models.IntegerField()
    bbcid = models.IntegerField()
    bbeid = models.IntegerField()
    actflag = models.CharField(max_length=50)
    changed = models.DateTimeField()
    created = models.DateField()
    secid = models.IntegerField()
    issid = models.IntegerField()
    isin = models.CharField(max_length=100)
    uscode = models.CharField(max_length=100, blank=True, null=True)
    issuername = models.CharField(max_length=100)
    cntryofincorp = models.CharField(max_length=100)
    sic = models.CharField(max_length=100, blank=True, null=True)
    cik = models.CharField(max_length=100, blank=True, null=True)
    indusid = models.CharField(max_length=100, blank=True, null=True)
    sectycd = models.CharField(max_length=100)
    securitydesc = models.CharField(max_length=100)
    parvalue = models.CharField(max_length=100, blank=True, null=True)
    pvcurrency = models.CharField(max_length=100)
    statusflag = models.CharField(max_length=100)
    primaryexchgcd = models.CharField(max_length=100, blank=True, null=True)
    bbgcurrency = models.CharField(max_length=100, blank=True, null=True)
    bbgcompositeglobalid = models.CharField(max_length=100, blank=True, null=True)
    bbgcompositeticker = models.CharField(max_length=100, blank=True, null=True)
    bbgglobalid = models.CharField(max_length=100, blank=True, null=True)
    bbgexchangeticker = models.CharField(max_length=100, blank=True, null=True)
    structcd = models.CharField(max_length=100, blank=True, null=True)
    exchgcntry = models.CharField(max_length=100)
    exchgcd = models.CharField(max_length=100)
    mic = models.CharField(max_length=100)
    micseg = models.CharField(max_length=100, blank=True, null=True)
    localcode = models.CharField(max_length=100, blank=True, null=True)
    liststatus = models.CharField(max_length=100, blank=True, null=True)
    date1type = models.CharField(max_length=100, blank=True, null=True)
    date1 = models.CharField(max_length=100, blank=True, null=True)
    date2type = models.CharField(max_length=100, blank=True, null=True)
    date2 = models.CharField(max_length=100, blank=True, null=True)
    date3type = models.CharField(max_length=100, blank=True, null=True)
    date3 = models.CharField(max_length=100, blank=True, null=True)
    date4type = models.CharField(max_length=100, blank=True, null=True)
    date4 = models.CharField(max_length=100, blank=True, null=True)
    date5type = models.CharField(max_length=100, blank=True, null=True)
    date5 = models.CharField(max_length=100, blank=True, null=True)
    date6type = models.CharField(max_length=100, blank=True, null=True)
    date6 = models.CharField(max_length=100, blank=True, null=True)
    date7type = models.CharField(max_length=100, blank=True, null=True)
    date7 = models.CharField(max_length=100, blank=True, null=True)
    date8type = models.CharField(max_length=100, blank=True, null=True)
    date8 = models.CharField(max_length=100, blank=True, null=True)
    date9type = models.CharField(max_length=100, blank=True, null=True)
    date9 = models.CharField(max_length=100, blank=True, null=True)
    date10type = models.CharField(max_length=100, blank=True, null=True)
    date10 = models.CharField(max_length=100, blank=True, null=True)
    date11type = models.CharField(max_length=100, blank=True, null=True)
    date11 = models.CharField(max_length=100, blank=True, null=True)
    date12type = models.CharField(max_length=100, blank=True, null=True)
    date12 = models.CharField(max_length=100, blank=True, null=True)
    paytype = models.CharField(max_length=100, blank=True, null=True)
    rdid = models.CharField(max_length=100, blank=True, null=True)
    priority = models.CharField(max_length=100, blank=True, null=True)
    defaultopt = models.CharField(max_length=100, blank=True, null=True)
    outturnsecid = models.CharField(max_length=100, blank=True, null=True)
    outturnisin = models.CharField(max_length=100, blank=True, null=True)
    ratioold = models.CharField(max_length=100, blank=True, null=True)
    rationew = models.CharField(max_length=100, blank=True, null=True)
    fractions = models.CharField(max_length=100, blank=True, null=True)
    currency = models.CharField(max_length=100, blank=True, null=True)
    rate1type = models.CharField(max_length=100, blank=True, null=True)
    rate1 = models.CharField(max_length=100, blank=True, null=True)
    rate2type = models.CharField(max_length=100, blank=True, null=True)
    rate2 = models.CharField(max_length=100, blank=True, null=True)
    field1name = models.CharField(max_length=100, blank=True, null=True)
    field1 = models.CharField(max_length=100, blank=True, null=True)
    field2name = models.CharField(max_length=100, blank=True, null=True)
    field2 = models.CharField(max_length=100, blank=True, null=True)
    field3name = models.CharField(max_length=100, blank=True, null=True)
    field3 = models.CharField(max_length=100, blank=True, null=True)
    field4name = models.CharField(max_length=100, blank=True, null=True)
    field4 = models.CharField(max_length=100, blank=True, null=True)
    field5name = models.CharField(max_length=100, blank=True, null=True)
    field5 = models.CharField(max_length=100, blank=True, null=True)
    field6name = models.CharField(max_length=100, blank=True, null=True)
    field6 = models.CharField(max_length=100, blank=True, null=True)
    field7name = models.CharField(max_length=100, blank=True, null=True)
    field7 = models.CharField(max_length=100, blank=True, null=True)
    field8name = models.CharField(max_length=100, blank=True, null=True)
    field8 = models.CharField(max_length=100, blank=True, null=True)
    field9name = models.CharField(max_length=100, blank=True, null=True)
    field9 = models.CharField(max_length=100, blank=True, null=True)
    field10name = models.CharField(max_length=100, blank=True, null=True)
    field10 = models.CharField(max_length=100, blank=True, null=True)
    field11name = models.CharField(max_length=100, blank=True, null=True)
    field11 = models.CharField(max_length=100, blank=True, null=True)
    field12name = models.CharField(max_length=100, blank=True, null=True)
    field12 = models.CharField(max_length=100, blank=True, null=True)
    field13name = models.CharField(max_length=100, blank=True, null=True)
    field13 = models.CharField(max_length=100, blank=True, null=True)
    field14name = models.CharField(max_length=100, blank=True, null=True)
    field14 = models.CharField(max_length=100, blank=True, null=True)
    field15name = models.CharField(max_length=100, blank=True, null=True)
    field15 = models.CharField(max_length=100, blank=True, null=True)
    field16name = models.CharField(max_length=100, blank=True, null=True)
    field16 = models.CharField(max_length=100, blank=True, null=True)
    field17name = models.CharField(max_length=100, blank=True, null=True)
    field17 = models.CharField(max_length=100, blank=True, null=True)
    field18name = models.CharField(max_length=100, blank=True, null=True)
    field18 = models.CharField(max_length=100, blank=True, null=True)
    field19name = models.CharField(max_length=100, blank=True, null=True)
    field19 = models.CharField(max_length=100, blank=True, null=True)
    field20name = models.CharField(max_length=100, blank=True, null=True)
    field20 = models.CharField(max_length=100, blank=True, null=True)
    field21name = models.CharField(max_length=100, blank=True, null=True)
    field21 = models.CharField(max_length=100, blank=True, null=True)
    field22name = models.CharField(max_length=100, blank=True, null=True)
    field22 = models.CharField(max_length=100, blank=True, null=True)
    field23name = models.CharField(max_length=100, blank=True, null=True)
    field23 = models.CharField(max_length=100, blank=True, null=True)
    field24name = models.CharField(max_length=100, blank=True, null=True)
    field24 = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'edi_raw'


class EdiRaw1(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    insert_date = models.DateTimeField()
    edi_filename = models.CharField(db_column='EDI_filename', max_length=100)  # Field name made lowercase.
    eventcd = models.CharField(max_length=50)
    eventid = models.IntegerField()
    optionid = models.SmallIntegerField()
    serialid = models.SmallIntegerField()
    scexhid = models.IntegerField()
    bbcid = models.IntegerField()
    bbeid = models.IntegerField()
    actflag = models.CharField(max_length=50)
    changed = models.DateTimeField()
    created = models.DateField()
    secid = models.IntegerField()
    issid = models.IntegerField()
    isin = models.CharField(max_length=100)
    uscode = models.CharField(max_length=100, blank=True, null=True)
    issuername = models.CharField(max_length=100)
    cntryofincorp = models.CharField(max_length=100)
    sic = models.CharField(max_length=100, blank=True, null=True)
    cik = models.CharField(max_length=100, blank=True, null=True)
    indusid = models.CharField(max_length=100, blank=True, null=True)
    sectycd = models.CharField(max_length=100)
    securitydesc = models.CharField(max_length=100)
    parvalue = models.CharField(max_length=100, blank=True, null=True)
    pvcurrency = models.CharField(max_length=100)
    statusflag = models.CharField(max_length=100)
    primaryexchgcd = models.CharField(max_length=100, blank=True, null=True)
    bbgcurrency = models.CharField(max_length=100, blank=True, null=True)
    bbgcompositeglobalid = models.CharField(max_length=100, blank=True, null=True)
    bbgcompositeticker = models.CharField(max_length=100, blank=True, null=True)
    bbgglobalid = models.CharField(max_length=100, blank=True, null=True)
    bbgexchangeticker = models.CharField(max_length=100, blank=True, null=True)
    structcd = models.CharField(max_length=100, blank=True, null=True)
    exchgcntry = models.CharField(max_length=100)
    exchgcd = models.CharField(max_length=100)
    mic = models.CharField(max_length=100)
    micseg = models.CharField(max_length=100, blank=True, null=True)
    localcode = models.CharField(max_length=100, blank=True, null=True)
    liststatus = models.CharField(max_length=100, blank=True, null=True)
    date1type = models.CharField(max_length=100, blank=True, null=True)
    date1 = models.CharField(max_length=100, blank=True, null=True)
    date2type = models.CharField(max_length=100, blank=True, null=True)
    date2 = models.CharField(max_length=100, blank=True, null=True)
    date3type = models.CharField(max_length=100, blank=True, null=True)
    date3 = models.CharField(max_length=100, blank=True, null=True)
    date4type = models.CharField(max_length=100, blank=True, null=True)
    date4 = models.CharField(max_length=100, blank=True, null=True)
    date5type = models.CharField(max_length=100, blank=True, null=True)
    date5 = models.CharField(max_length=100, blank=True, null=True)
    date6type = models.CharField(max_length=100, blank=True, null=True)
    date6 = models.CharField(max_length=100, blank=True, null=True)
    date7type = models.CharField(max_length=100, blank=True, null=True)
    date7 = models.CharField(max_length=100, blank=True, null=True)
    date8type = models.CharField(max_length=100, blank=True, null=True)
    date8 = models.CharField(max_length=100, blank=True, null=True)
    date9type = models.CharField(max_length=100, blank=True, null=True)
    date9 = models.CharField(max_length=100, blank=True, null=True)
    date10type = models.CharField(max_length=100, blank=True, null=True)
    date10 = models.CharField(max_length=100, blank=True, null=True)
    date11type = models.CharField(max_length=100, blank=True, null=True)
    date11 = models.CharField(max_length=100, blank=True, null=True)
    date12type = models.CharField(max_length=100, blank=True, null=True)
    date12 = models.CharField(max_length=100, blank=True, null=True)
    paytype = models.CharField(max_length=100, blank=True, null=True)
    rdid = models.CharField(max_length=100, blank=True, null=True)
    priority = models.CharField(max_length=100, blank=True, null=True)
    defaultopt = models.CharField(max_length=100, blank=True, null=True)
    outturnsecid = models.CharField(max_length=100, blank=True, null=True)
    outturnisin = models.CharField(max_length=100, blank=True, null=True)
    ratioold = models.CharField(max_length=100, blank=True, null=True)
    rationew = models.CharField(max_length=100, blank=True, null=True)
    fractions = models.CharField(max_length=100, blank=True, null=True)
    currency = models.CharField(max_length=100, blank=True, null=True)
    rate1type = models.CharField(max_length=100, blank=True, null=True)
    rate1 = models.CharField(max_length=100, blank=True, null=True)
    rate2type = models.CharField(max_length=100, blank=True, null=True)
    rate2 = models.CharField(max_length=100, blank=True, null=True)
    field1name = models.CharField(max_length=100, blank=True, null=True)
    field1 = models.CharField(max_length=100, blank=True, null=True)
    field2name = models.CharField(max_length=100, blank=True, null=True)
    field2 = models.CharField(max_length=100, blank=True, null=True)
    field3name = models.CharField(max_length=100, blank=True, null=True)
    field3 = models.CharField(max_length=100, blank=True, null=True)
    field4name = models.CharField(max_length=100, blank=True, null=True)
    field4 = models.CharField(max_length=100, blank=True, null=True)
    field5name = models.CharField(max_length=100, blank=True, null=True)
    field5 = models.CharField(max_length=100, blank=True, null=True)
    field6name = models.CharField(max_length=100, blank=True, null=True)
    field6 = models.CharField(max_length=100, blank=True, null=True)
    field7name = models.CharField(max_length=100, blank=True, null=True)
    field7 = models.CharField(max_length=100, blank=True, null=True)
    field8name = models.CharField(max_length=100, blank=True, null=True)
    field8 = models.CharField(max_length=100, blank=True, null=True)
    field9name = models.CharField(max_length=100, blank=True, null=True)
    field9 = models.CharField(max_length=100, blank=True, null=True)
    field10name = models.CharField(max_length=100, blank=True, null=True)
    field10 = models.CharField(max_length=100, blank=True, null=True)
    field11name = models.CharField(max_length=100, blank=True, null=True)
    field11 = models.CharField(max_length=100, blank=True, null=True)
    field12name = models.CharField(max_length=100, blank=True, null=True)
    field12 = models.CharField(max_length=100, blank=True, null=True)
    field13name = models.CharField(max_length=100, blank=True, null=True)
    field13 = models.CharField(max_length=100, blank=True, null=True)
    field14name = models.CharField(max_length=100, blank=True, null=True)
    field14 = models.CharField(max_length=100, blank=True, null=True)
    field15name = models.CharField(max_length=100, blank=True, null=True)
    field15 = models.CharField(max_length=100, blank=True, null=True)
    field16name = models.CharField(max_length=100, blank=True, null=True)
    field16 = models.CharField(max_length=100, blank=True, null=True)
    field17name = models.CharField(max_length=100, blank=True, null=True)
    field17 = models.CharField(max_length=100, blank=True, null=True)
    field18name = models.CharField(max_length=100, blank=True, null=True)
    field18 = models.CharField(max_length=100, blank=True, null=True)
    field19name = models.CharField(max_length=100, blank=True, null=True)
    field19 = models.CharField(max_length=100, blank=True, null=True)
    field20name = models.CharField(max_length=100, blank=True, null=True)
    field20 = models.CharField(max_length=100, blank=True, null=True)
    field21name = models.CharField(max_length=100, blank=True, null=True)
    field21 = models.CharField(max_length=100, blank=True, null=True)
    field22name = models.CharField(max_length=100, blank=True, null=True)
    field22 = models.CharField(max_length=100, blank=True, null=True)
    field23name = models.CharField(max_length=100, blank=True, null=True)
    field23 = models.CharField(max_length=100, blank=True, null=True)
    field24name = models.CharField(max_length=100, blank=True, null=True)
    field24 = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'edi_raw1'


class EdiRaw2(models.Model):
    id = models.AutoField(db_column='ID')  # Field name made lowercase.
    insert_date = models.DateTimeField()
    edi_filename = models.CharField(db_column='EDI_filename', max_length=100)  # Field name made lowercase.
    eventcd = models.CharField(max_length=50)
    eventid = models.IntegerField()
    optionid = models.SmallIntegerField()
    serialid = models.SmallIntegerField()
    scexhid = models.IntegerField()
    bbcid = models.IntegerField()
    bbeid = models.IntegerField()
    actflag = models.CharField(max_length=50)
    changed = models.DateTimeField()
    created = models.DateField()
    secid = models.IntegerField()
    issid = models.IntegerField()
    isin = models.CharField(max_length=100)
    uscode = models.CharField(max_length=100, blank=True, null=True)
    issuername = models.CharField(max_length=100)
    cntryofincorp = models.CharField(max_length=100)
    sic = models.CharField(max_length=100, blank=True, null=True)
    cik = models.CharField(max_length=100, blank=True, null=True)
    indusid = models.CharField(max_length=100, blank=True, null=True)
    sectycd = models.CharField(max_length=100)
    securitydesc = models.CharField(max_length=100)
    parvalue = models.CharField(max_length=100, blank=True, null=True)
    pvcurrency = models.CharField(max_length=100)
    statusflag = models.CharField(max_length=100)
    primaryexchgcd = models.CharField(max_length=100, blank=True, null=True)
    bbgcurrency = models.CharField(max_length=100, blank=True, null=True)
    bbgcompositeglobalid = models.CharField(max_length=100, blank=True, null=True)
    bbgcompositeticker = models.CharField(max_length=100, blank=True, null=True)
    bbgglobalid = models.CharField(max_length=100, blank=True, null=True)
    bbgexchangeticker = models.CharField(max_length=100, blank=True, null=True)
    structcd = models.CharField(max_length=100, blank=True, null=True)
    exchgcntry = models.CharField(max_length=100)
    exchgcd = models.CharField(max_length=100)
    mic = models.CharField(max_length=100)
    micseg = models.CharField(max_length=100, blank=True, null=True)
    localcode = models.CharField(max_length=100, blank=True, null=True)
    liststatus = models.CharField(max_length=100, blank=True, null=True)
    date1type = models.CharField(max_length=100, blank=True, null=True)
    date1 = models.CharField(max_length=100, blank=True, null=True)
    date2type = models.CharField(max_length=100, blank=True, null=True)
    date2 = models.CharField(max_length=100, blank=True, null=True)
    date3type = models.CharField(max_length=100, blank=True, null=True)
    date3 = models.CharField(max_length=100, blank=True, null=True)
    date4type = models.CharField(max_length=100, blank=True, null=True)
    date4 = models.CharField(max_length=100, blank=True, null=True)
    date5type = models.CharField(max_length=100, blank=True, null=True)
    date5 = models.CharField(max_length=100, blank=True, null=True)
    date6type = models.CharField(max_length=100, blank=True, null=True)
    date6 = models.CharField(max_length=100, blank=True, null=True)
    date7type = models.CharField(max_length=100, blank=True, null=True)
    date7 = models.CharField(max_length=100, blank=True, null=True)
    date8type = models.CharField(max_length=100, blank=True, null=True)
    date8 = models.CharField(max_length=100, blank=True, null=True)
    date9type = models.CharField(max_length=100, blank=True, null=True)
    date9 = models.CharField(max_length=100, blank=True, null=True)
    date10type = models.CharField(max_length=100, blank=True, null=True)
    date10 = models.CharField(max_length=100, blank=True, null=True)
    date11type = models.CharField(max_length=100, blank=True, null=True)
    date11 = models.CharField(max_length=100, blank=True, null=True)
    date12type = models.CharField(max_length=100, blank=True, null=True)
    date12 = models.CharField(max_length=100, blank=True, null=True)
    paytype = models.CharField(max_length=100, blank=True, null=True)
    rdid = models.CharField(max_length=100, blank=True, null=True)
    priority = models.CharField(max_length=100, blank=True, null=True)
    defaultopt = models.CharField(max_length=100, blank=True, null=True)
    outturnsecid = models.CharField(max_length=100, blank=True, null=True)
    outturnisin = models.CharField(max_length=100, blank=True, null=True)
    ratioold = models.CharField(max_length=100, blank=True, null=True)
    rationew = models.CharField(max_length=100, blank=True, null=True)
    fractions = models.CharField(max_length=100, blank=True, null=True)
    currency = models.CharField(max_length=100, blank=True, null=True)
    rate1type = models.CharField(max_length=100, blank=True, null=True)
    rate1 = models.CharField(max_length=100, blank=True, null=True)
    rate2type = models.CharField(max_length=100, blank=True, null=True)
    rate2 = models.CharField(max_length=100, blank=True, null=True)
    field1name = models.CharField(max_length=100, blank=True, null=True)
    field1 = models.CharField(max_length=100, blank=True, null=True)
    field2name = models.CharField(max_length=100, blank=True, null=True)
    field2 = models.CharField(max_length=100, blank=True, null=True)
    field3name = models.CharField(max_length=100, blank=True, null=True)
    field3 = models.CharField(max_length=100, blank=True, null=True)
    field4name = models.CharField(max_length=100, blank=True, null=True)
    field4 = models.CharField(max_length=100, blank=True, null=True)
    field5name = models.CharField(max_length=100, blank=True, null=True)
    field5 = models.CharField(max_length=100, blank=True, null=True)
    field6name = models.CharField(max_length=100, blank=True, null=True)
    field6 = models.CharField(max_length=100, blank=True, null=True)
    field7name = models.CharField(max_length=100, blank=True, null=True)
    field7 = models.CharField(max_length=100, blank=True, null=True)
    field8name = models.CharField(max_length=100, blank=True, null=True)
    field8 = models.CharField(max_length=100, blank=True, null=True)
    field9name = models.CharField(max_length=100, blank=True, null=True)
    field9 = models.CharField(max_length=100, blank=True, null=True)
    field10name = models.CharField(max_length=100, blank=True, null=True)
    field10 = models.CharField(max_length=100, blank=True, null=True)
    field11name = models.CharField(max_length=100, blank=True, null=True)
    field11 = models.CharField(max_length=100, blank=True, null=True)
    field12name = models.CharField(max_length=100, blank=True, null=True)
    field12 = models.CharField(max_length=100, blank=True, null=True)
    field13name = models.CharField(max_length=100, blank=True, null=True)
    field13 = models.CharField(max_length=100, blank=True, null=True)
    field14name = models.CharField(max_length=100, blank=True, null=True)
    field14 = models.CharField(max_length=100, blank=True, null=True)
    field15name = models.CharField(max_length=100, blank=True, null=True)
    field15 = models.CharField(max_length=100, blank=True, null=True)
    field16name = models.CharField(max_length=100, blank=True, null=True)
    field16 = models.CharField(max_length=100, blank=True, null=True)
    field17name = models.CharField(max_length=100, blank=True, null=True)
    field17 = models.CharField(max_length=100, blank=True, null=True)
    field18name = models.CharField(max_length=100, blank=True, null=True)
    field18 = models.CharField(max_length=100, blank=True, null=True)
    field19name = models.CharField(max_length=100, blank=True, null=True)
    field19 = models.CharField(max_length=100, blank=True, null=True)
    field20name = models.CharField(max_length=100, blank=True, null=True)
    field20 = models.CharField(max_length=100, blank=True, null=True)
    field21name = models.CharField(max_length=100, blank=True, null=True)
    field21 = models.CharField(max_length=100, blank=True, null=True)
    field22name = models.CharField(max_length=100, blank=True, null=True)
    field22 = models.CharField(max_length=100, blank=True, null=True)
    field23name = models.CharField(max_length=100, blank=True, null=True)
    field23 = models.CharField(max_length=100, blank=True, null=True)
    field24name = models.CharField(max_length=100, blank=True, null=True)
    field24 = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'edi_raw2'


class FdsCa(models.Model):
    id = models.AutoField(db_column='ID')  # Field name made lowercase.
    createddate = models.DateTimeField(db_column='createdDate', blank=True, null=True)  # Field name made lowercase.
    modifieddate = models.DateTimeField(db_column='modifiedDate', blank=True, null=True)  # Field name made lowercase.
    edi_isin = models.CharField(max_length=20, blank=True, null=True)
    isin = models.CharField(max_length=20, blank=True, null=True)
    sedol = models.CharField(max_length=20, blank=True, null=True)
    sedol_startdate = models.CharField(max_length=20, blank=True, null=True)
    fds_ticker = models.CharField(max_length=20, blank=True, null=True)
    fsym_id = models.CharField(max_length=10, blank=True, null=True)
    security_name = models.TextField(blank=True, null=True)
    fref_listing_exchange = models.CharField(max_length=10, blank=True, null=True)
    mic_op_exchange_code = models.CharField(max_length=10, blank=True, null=True)
    ca_type = models.CharField(max_length=20, blank=True, null=True)
    exdate = models.CharField(max_length=10, blank=True, null=True)
    p_divs_pd = models.FloatField(blank=True, null=True)
    p_split_factor = models.FloatField(blank=True, null=True)
    spinoff_factor = models.FloatField(blank=True, null=True)
    currency = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'fds_ca'


class FdsCa1(models.Model):
    id = models.AutoField(db_column='ID')  # Field name made lowercase.
    createddate = models.DateTimeField(db_column='createdDate', blank=True, null=True)  # Field name made lowercase.
    modifieddate = models.DateTimeField(db_column='modifiedDate', blank=True, null=True)  # Field name made lowercase.
    edi_isin = models.CharField(max_length=20, blank=True, null=True)
    isin = models.CharField(max_length=20, blank=True, null=True)
    sedol = models.CharField(max_length=20, blank=True, null=True)
    sedol_startdate = models.CharField(max_length=20, blank=True, null=True)
    fds_ticker = models.CharField(max_length=20, blank=True, null=True)
    fsym_id = models.CharField(max_length=10, blank=True, null=True)
    security_name = models.TextField(blank=True, null=True)
    fref_listing_exchange = models.CharField(max_length=10, blank=True, null=True)
    mic_op_exchange_code = models.CharField(max_length=10, blank=True, null=True)
    ca_type = models.CharField(max_length=20, blank=True, null=True)
    exdate = models.CharField(max_length=10, blank=True, null=True)
    p_divs_pd = models.FloatField(blank=True, null=True)
    p_split_factor = models.FloatField(blank=True, null=True)
    spinoff_factor = models.FloatField(blank=True, null=True)
    currency = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'fds_ca1'


class MasterIsin(models.Model):
    id = models.AutoField(db_column='ID')  # Field name made lowercase.
    isin = models.CharField(db_column='ISIN', max_length=50)  # Field name made lowercase.
    mic = models.CharField(max_length=10)
    active = models.BooleanField()

    class Meta:
        managed = False
        db_table = 'master_isin'
